title: Cognitio Arcanum
email: tiagolinhares051@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Este é um blog onde falaremos de assuntos relacionados a dados, tecnologia, programação, desenvolvimento, etc.
#header-img: "img/home-bg.jpg"
#header-text: "Cognitio Arcanum"
baseurl: "/linhares015.github.io"
url: "https://linhares015.github.io"

#twitter_username: jekyllrb
github_username: Linhares015

# paginate: 5 # Número de posts por página
# paginate_path: "/page:num/"

jekyll-archives:
  enabled:
    - categories
  layout: 'archive'
  permalinks:
    category: '/category/:name/'

# Build settings
theme: minima
plugins:
  - jekyll-feed
  #- jekyll-paginate
  - jekyll-archives
verbose: true