title: Cognitio Arcanum
email: tiagolinhares051@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Este é um blog onde falaremos de assuntos relacionados a dados, tecnologia, programação, desenvolvimento, etc.

baseurl: ""
url: "https://linhares015.github.io"

github_username: Linhares015

jekyll-archives:
  enabled:
    - categories
  layout: 'archive'
  permalinks:
    category: '/category/:name/'

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-archives
verbose: true