source "https://rubygems.org"
gem "jekyll", "~> 3.9.3"
gem "minima", "~> 2.5.1"
gem "jekyll-feed"
gem "jekyll-seo-tag"
gem "jekyll-coffeescript"
gem "jekyll-commonmark-ghpages"
gem "jekyll-gist"
gem "jekyll-github-metadata"
gem "jekyll-paginate"
gem "jekyll-relative-links"
gem "jekyll-optional-front-matter"
gem "jekyll-readme-index"
gem "jekyll-default-layout"
gem "jekyll-titles-from-headings"
gem "bundler", "2.4.19"
