site_name: Tiago Linhares
site_description: Tiago Linhares personal blog
site_author: Tiago Linhares
theme:
  name: material
  logo: 'images/logo.png'
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Mudar para modo escuro
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Mudar para modo claro
