name: Jekyll site CI

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'

    - name: Update Bundler
      run: gem install bundler:2.4.19

    - name: Install dependencies
      run: bundle install

    - name: Build Jekyll site
      uses: actions/jekyll-build-pages@v1
      
    - name: Build site
      run: bundle exec jekyll build
